spring.application.name=myown


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect