spring.application.name=myown

#Desa
#spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:32603/railway?options=-c%20TimeZone=UTC
#spring.datasource.username=postgres
#spring.datasource.password=qgSoUWqwRaktWjKGRNhGNUPXbQtfvXVc
#prod
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

##desa
#jwt.secret="k7Qm2vXpL9nRwZ4tYhB6cJdF8sEaU1oN"
#jwt.expiration-ms=3600000
##prod
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect